# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/FastHtml-nbdev',
                'doc_host': 'https://PaulLockett.github.io',
                'git_url': 'https://github.com/PaulLockett/FastHtml-nbdev',
                'lib_path': 'FastHtml_nbdev'},
  'syms': {'FastHtml_nbdev.core': {'FastHtml_nbdev.core.foo': ('core.html#foo', 'FastHtml_nbdev/core.py')}}}
